/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("PurchaseRequestsListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onThePurchaseRequestsListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onThePurchaseRequestsListGenerated.onFilterBar().iCheckFilterField({ property: "department" });
            Then.onThePurchaseRequestsListGenerated.onFilterBar().iCheckFilterField({ property: "status" });
            Then.onThePurchaseRequestsListGenerated.onFilterBar().iCheckFilterField({ property: "requesterName" });
            Then.onThePurchaseRequestsListGenerated.onFilterBar().iCheckFilterField({ property: "totalAmount" });
            Then.onThePurchaseRequestsListGenerated.onFilterBar().iCheckFilterField({ property: "requestDate" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onThePurchaseRequestsListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onThePurchaseRequestsListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onThePurchaseRequestsListGenerated.onTable(defaultTableId).iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onThePurchaseRequestsListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"requestNo":{"header":"Request Number"},"requesterName":{"header":"Requester Name"},"department":{"header":"Department"},"requestDate":{"header":"Request Date"},"totalAmount":{"header":"Total Amount"},"status":{"header":"Status"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onThePurchaseRequestsListGenerated.onFilterBar().iExecuteSearch();
            Then.onThePurchaseRequestsListGenerated.onTable(defaultTableId).iCheckRows();
            When.onThePurchaseRequestsListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onThePurchaseRequestsObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});