/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("PurchaseRequestsObjectPageObjectPage journey");

        opaTest("Navigate to PurchaseRequestsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onThePurchaseRequestsListGenerated.onFilterBar().iExecuteSearch();
            Then.onThePurchaseRequestsListGenerated.onTable().iCheckRows();
            When.onThePurchaseRequestsListGenerated.onTable().iPressRow(0);

            Then.onThePurchaseRequestsObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onThePurchaseRequestsObjectPageGenerated.iCheckNumberOfSections(3);
            When.onThePurchaseRequestsObjectPageGenerated.iPressSectionIconTabFilterButton("FieldGroup::General");
            Then.onThePurchaseRequestsObjectPageGenerated.iCheckSection({ section: "FieldGroup::General" });
            Then.onThePurchaseRequestsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "requestNo" });
            Then.onThePurchaseRequestsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "requesterName" });
            Then.onThePurchaseRequestsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "department" });
            Then.onThePurchaseRequestsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "requestDate" });
            Then.onThePurchaseRequestsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "currency" });
            Then.onThePurchaseRequestsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "totalAmount" });
            Then.onThePurchaseRequestsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "status" });
            Then.onThePurchaseRequestsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "approver" });
            When.onThePurchaseRequestsObjectPageGenerated.iPressSectionIconTabFilterButton("items::LineItem");
            Then.onThePurchaseRequestsObjectPageGenerated.iCheckSection({ section: "items::LineItem" });
            When.onThePurchaseRequestsObjectPageGenerated.iPressSectionIconTabFilterButton("FieldGroup::Audit");
            Then.onThePurchaseRequestsObjectPageGenerated.iCheckSection({ section: "FieldGroup::Audit" });
            Then.onThePurchaseRequestsObjectPageGenerated.onForm({ section: "FieldGroup::Audit" }).iCheckField({ property: "createdBy" });
            Then.onThePurchaseRequestsObjectPageGenerated.onForm({ section: "FieldGroup::Audit" }).iCheckField({ property: "createdAt" });
            Then.onThePurchaseRequestsObjectPageGenerated.onForm({ section: "FieldGroup::Audit" }).iCheckField({ property: "modifiedBy" });
            Then.onThePurchaseRequestsObjectPageGenerated.onForm({ section: "FieldGroup::Audit" }).iCheckField({ property: "modifiedAt" });
            Then.onThePurchaseRequestsObjectPageGenerated.onForm({ section: "FieldGroup::Audit" }).iCheckField({ property: "approvedBy" });
            Then.onThePurchaseRequestsObjectPageGenerated.onForm({ section: "FieldGroup::Audit" }).iCheckField({ property: "approvedAt" });
            Then.onThePurchaseRequestsObjectPageGenerated.onForm({ section: "FieldGroup::Audit" }).iCheckField({ property: "rejectedBy" });
            Then.onThePurchaseRequestsObjectPageGenerated.onForm({ section: "FieldGroup::Audit" }).iCheckField({ property: "rejectedAt" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});